### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by MrMaslowski** [RauschRobin/AdvancedSoftwareEngineering#27]
New shared file for storing all API-Keys

**Comment by RauschRobin** [comment]
More information: We need to implement a mechanism to store and share api key between team members. We do not want to hardcode the api keys. They need to stay private. 
Example Implementation: share api_keys.yaml file via teams, update if necessary & load at runtime. Also store the filename api_keys.yaml in the .gitignore file so that we dont accidentally push the keys into our public repository
